name: NoChunk
main: com.mcmiddleearth.nochunks.NoChunks
version: 1.0.0
load: STARTUP
authors: [DonoA,Eriol_Eandur]

permissions:
    noChunks.ignore:
        description: Allows to ignore NoChunks map borders
        default: op